---#Instala Nginx
- name: Instala nginx
  yum: name=nginx state=present

- name: Inicia nginx
  service: name=nginx state=started enabled=yes

- name: Copio la pagina en el servidor
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html
